### ISSUE TITLE
您好，docs中的一些图片无法显示，请问能公布完整版的吗？谢谢！

### ISSUE THREAD

**Issue by AnqiLeee** [NLPInBLCU/ChineseSemanticDependencyDocument#1]
docs中的图片链接无效，您可以公布一份完整版语义标注细则吗？感谢！

**Comment by Youarerare** [comment]
指的是具体哪一张图片呢，我马上去修改。文档内容可以看 csdp-doc.readthedocs.io/zh_cn/latest/ 或者 https://csdp-doc.github.io/

**Comment by AnqiLeee** [comment]
> 指的是具体哪一张图片呢，我马上去修改。文档内容可以看 csdp-doc.readthedocs.io/zh_cn/latest/ 或者 https://csdp-doc.github.io/

非常感谢您的及时回复！
![image](https://user-images.githubusercontent.com/45265448/93549790-a9f76a80-f99c-11ea-9b5d-e2b7d8a12412.png)
类似于这里，图片link点击后会跳转到404页面

还想请问您一下，根据docs中提到的两版语义依存分析语料，可以在哪里下载到呢？谢谢！
![image](https://user-images.githubusercontent.com/45265448/93549886-e034ea00-f99c-11ea-844c-8ad78bb0c21e.png)

**Comment by AnqiLeee** [comment]
还想请问~在标注语料时使用的标注工具是什么呢？谢谢分享！

**Comment by Youarerare** [comment]
语料地址：https://github.com/HIT-SCIR/SemEval-2016
工具：内部工具，暂时无法公开

**Comment by AnqiLeee** [comment]
好的收到！谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NLPInBLCU/ChineseSemanticDependencyDocument"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月18日(星期五) 中午11:08
收件人:&nbsp;"NLPInBLCU/ChineseSemanticDependencyDocument"<ChineseSemanticDependencyDocument@noreply.github.com&gt;;
抄送:&nbsp;"Angelee"<260752732@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NLPInBLCU/ChineseSemanticDependencyDocument] 您好，docs中的一些图片无法显示，请问能公布完整版的吗？谢谢！ (#1)





 
语料地址：https://github.com/HIT-SCIR/SemEval-2016
 工具：内部工具，暂时无法公开
